### ISSUE TITLE
ionic cordova build android Issue 

### ISSUE THREAD

**Issue by donacoba090909** [blinks32/Ionic-3-and-4-Taxi-booking-App-Similar-to-Uber-and-Taxify.-Contains-User-Driver--and-web-admin.#3]
Hi blinks32,
 brilliant work. btw I tried to execute the build android command but it gives me like this error
![issuescreen](https://user-images.githubusercontent.com/20560079/46079601-edb69f80-c1da-11e8-876b-3181bae73ac8.PNG)

**then I tried to edit the graddle project properties  this way:**
cordova.system.library.4=com.google.android.gms:play-services-maps:+
cordova.system.library.5=com.google.android.gms:play-services-location:+
cordova.system.library.6=com.android.support:support-core-utils:26.+

here's the error:

![image](https://user-images.githubusercontent.com/20560079/46080042-2a36cb00-c1dc-11e8-9361-ac23a24338f6.png)

**Comment by blinks32** [comment]
This is just a sample, Please purchase the full source code.
